### PR TITLE
Associative Arrays tweak to the Model Class. 

### PR DESCRIPTION
**Pull request by asteiner-idsync**
-Added a private function to \Connect\Model to allow proper conversion of index arrays to associative arrays.
- Tweaked the set() function to make use of this change.
- Tweaked the arrayize() function to make use of this change.

### CODE REVIEW

**Comment by marcserrat** [comment]
Hi asteiner-idsync,

as you saw, your pull request brakes all testings and brakes backwards compatibility, something extremely important to keep.

Additionally, can you please provide business case where you will need it? any reason on going over the array in associative way and not using getParameterByID or getItemByMPN?

thanks for your collaboration

**Comment by asteiner-idsync** [comment]
Well, going from the example script and readme, I should have been able to access the parameter via a named index of an associated array. 
```getParameterByID()``` Doesn't appear anywhere in the those... only the tests with absolutely no text on how to properly use it, or if it was just an internal overload for testing. 

I now that I'm aware of those two functions, I shall use them. I'll close out the pull request, as it breaks the functionality of those two methods.

**Comment by marcserrat** [comment]
thanks

Please in case that you did not saw it, in vendor portal of connect you have a full featured example explaining additional information, this one can also be obtained here:
https://github.com/ingrammicro/fallball-quickstart-sample
last but not least, just in case you did not saw this, we have an skeleton for processors that may be usefull for you. This one available here (and in composer):
https://github.com/ingrammicro/connect-quickstart-template-for-php

thanks for your collaboration! i highly appreciate it!

**Comment by asteiner-idsync** [comment]
Wonderful! These will definitely help. Thanks for pointing them out.

**Pull request closed without merging**
